DROP DATABASE IF EXISTS cookbook_db;

CREATE DATABASE cookbook_db;
USE cookbook_db;

CREATE TABLE recipes (
    id int NOT NULL AUTO_INCREMENT,
    recipe_name VARCHAR(200) NOT NULL,
    ingredients VARCHAR(550),
    directions VARCHAR(550) NOT NULL,
    recipeImage VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE ingredients (
    id int NOT NULL AUTO_INCREMENT,
    name VARCHAR(200) NOT NULL,
    season VARCHAR(200) NULL,
    PRIMARY KEY (id)
);

INSERT INTO recipes (recipe_name, ingredients, directions, recipeImage)


-- TODO: '1,2,3' need to be split on the comma and conversted to an array referencing the ingredients table
VALUES
('Veggie burger', '[{"ingredients": 1, "amount": "2 cups"},{"ingredients": 2, "amount": "1/2lb"}]', 'Make the patty. Cook it.', '/public/uploads/img.png'),
('Fish tacos', '[{"ingredients": 3, "amount": "2 cups"},{"ingredients": 1, "amount": "1/2lb"}]', 'Cook the fish. Make the tacos.', '/public/uploads/img.png'),
('California rolls', '[{"ingredients": 2, "amount": "2 cups"},{"ingredients": 3, "amount": "1/2lb"}]', 'Cut the ingredients. Roll em.', '/public/uploads/img.png');


INSERT INTO ingredients (name, season)

VALUES
('Apples', 'Spring'),
('Apricots', 'Spring'),
('Asparagus', 'Spring'),
('Avocados', 'Spring'),
('Bananas', 'Spring'),
('Broccoli', 'Spring'),
('Cabbage', 'Spring'),
('Carrots', 'Spring'),
('Celery', 'Spring'),
('Collard Greens', 'Spring'),
('Garlic', 'Spring'),
('Kale', 'Spring'),
('Kiwifruit', 'Spring'),
('Lemons', 'Spring'),
('Lettuce', 'Spring'),
('Limes', 'Spring'),
('Mushrooms', 'Spring'),
('Onions', 'Spring'),
('Peas', 'Spring'),
('Pineapples', 'Spring'),
('Radishes', 'Spring'),
('Rhubarb', 'Spring'),
('Spinach', 'Spring'),
('Strawberries', 'Spring'),
('Swiss Chard', 'Spring'),
('Turnips', 'Spring'),
('Halibut', 'Spring'),
('Sablefish', 'Spring'),
('Beets', 'Summer'),
('Bell Peppers', 'Summer'),
('Blackberries', 'Summer'),
('Blueberries', 'Summer'),
('Cantaloupe', 'Summer'),
('Carrots', 'Summer'),
('Celery', 'Summer'),
('Cherries', 'Summer'),
('Corn', 'Summer'),
('Cucumbers', 'Summer'),
('Eggplant', 'Summer'),
('Garlic', 'Summer'),
('Green Beans', 'Summer'),
('Honeydew Melon', 'Summer'),
('Lemons', 'Summer'),
('Lima Beans', 'Summer'),
('Limes', 'Summer'),
('Mangos', 'Summer'),
('Okra', 'Summer'),
('Peaches', 'Summer'),
('Plums', 'Summer'),
('Raspberries', 'Summer'),
('Strawberries', 'Summer'),
('Summer Squash', 'Summer'),
('Tomatillos', 'Summer'),
('Tomatoes', 'Summer'),
('Watermelon', 'Summer'),
('Zucchini', 'Summer'),
('Albacore tuna', 'Summer'),
('Anchovies', 'Summer'),
('Dungeness crab', 'Summer'),
('Halibut', 'Summer'),
('Oregon pink shrimp', 'Summer'),
('Sablefish', 'Summer'),
('Green Beans', 'Fall'),
('Kale', 'Fall'),
('Kiwifruit', 'Fall'),
('Lemons', 'Fall'),
('Lettuce', 'Fall'),
('Limes', 'Fall'),
('Mangos', 'Fall'),
('Mushrooms', 'Fall'),
('Onions', 'Fall'),
('Parsnips', 'Fall'),
('Pears', 'Fall'),
('Peas', 'Fall'),
('Pineapples', 'Fall'),
('Potatoes', 'Fall'),
('Pumpkin', 'Fall'),
('Radishes', 'Fall'),
('Raspberries', 'Fall'),
('Rutabagas', 'Fall'),
('Spinach', 'Fall'),
('Sweet Potatoes', 'Fall'),
('Yams', 'Fall'),
('Swiss Chard', 'Fall'),
('Turnips', 'Fall'),
('Winter Squash', 'Fall'),
('Anchovies', 'Fall'),
('Dungeness crab', 'Fall'),
('Halibut', 'Fall'),
('Oregon pink shrimp', 'Fall'),
('Sablefish', 'Fall'),
('Spiny lobster', 'Fall'),
('Apples', 'Winter'),
('Avocados', 'Winter'),
('Bananas', 'Winter'),
('Beets', 'Winter'),
('Brussels Sprouts', 'Winter'),
('Cabbage', 'Winter'),
('Carrots', 'Winter'),
('Celery', 'Winter'),
('Collard Greens', 'Winter'),
('Grapefruit', 'Winter'),
('Kale', 'Winter'),
('Kiwifruit', 'Winter'),
('Leeks', 'Winter'),
('Lemons', 'Winter'),
('Limes', 'Winter'),
('Onions', 'Winter'),
('Oranges', 'Winter'),
('Parsnips', 'Winter'),
('Pears', 'Winter'),
('Pineapples', 'Winter'),
('Potatoes', 'Winter'),
('Pumpkin', 'Winter'),
('Rutabagas', 'Winter'),
('Sweet Potatoes', 'Winter'),
('Yams', 'Winter'),
('Swiss Chard', 'Winter'),
('Turnips', 'Winter'),
('Winter Squash', 'Winter'),
('Dungeness crab', 'Winter'),
('Spiny lobster', 'Winter');
