DROP DATABASE IF EXISTS cookbook_db;

CREATE DATABASE cookbook_db;
USE cookbook_db;

CREATE TABLE recipes (
    id int NOT NULL AUTO_INCREMENT,
    recipe_name VARCHAR(200) NOT NULL,
    ingredients VARCHAR(5000),
    directions VARCHAR(5000) NOT NULL,
    recipeImage VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE ingredients (
    id int NOT NULL AUTO_INCREMENT,
    name VARCHAR(200) NOT NULL,
    season VARCHAR(200) NULL,
    PRIMARY KEY (id)
);

INSERT INTO recipes (recipe_name, ingredients, directions, recipeImage)


-- TODO: '1,2,3' need to be split on the comma and conversted to an array referencing the ingredients table
VALUES
('Veggie burger', '[{"ingredients": 1, "amount": "2 cups"},{"ingredients": 2, "amount": "1/2lb"}]', 'Make the patty. Cook it.', '/uploads/img.png'),
('Fish tacos', '[{"ingredients": 3, "amount": "2 cups"},{"ingredients": 1, "amount": "1/2lb"}]', 'Cook the fish. Make the tacos.', '/uploads/img.png'),
('California rolls', '[{"ingredients": 2, "amount": "2 cups"},{"ingredients": 3, "amount": "1/2lb"}]', 'Cut the ingredients. Roll em.', '/uploads/img.png'),
('Shrimp & Rice','[{\"ingredients\":236,\"amount\":\"2 cups\"},{\"ingredients\":61,\"amount\":\"1 lb.\"},{\"ingredients\":245,\"amount\":\"2 Tbs.\"},{\"ingredients\":8,\"amount\":\"2 Whole\"},{\"ingredients\":123,\"amount\":\"1/4 tps.\"}]','Cook rice according to directions.  Peel and devein the shrimp.  Cook shrimp in the pan with butter, salt, and carrots.  Eat!','/uploads/img.png');


INSERT INTO ingredients (name, season)

VALUES
('Apples', 'Spring'),
('Apricots', 'Spring'),
('Asparagus', 'Spring'),
('Avocados', 'Spring'),
('Bananas', 'Spring'),
('Broccoli', 'Spring'),
('Cabbage', 'Spring'),
('Carrots', 'Spring'),
('Celery', 'Spring'),
('Collard Greens', 'Spring'),
('Garlic', 'Spring'),
('Kale', 'Spring'),
('Kiwifruit', 'Spring'),
('Lemons', 'Spring'),
('Lettuce', 'Spring'),
('Limes', 'Spring'),
('Mushrooms', 'Spring'),
('Onions', 'Spring'),
('Peas', 'Spring'),
('Pineapples', 'Spring'),
('Radishes', 'Spring'),
('Rhubarb', 'Spring'),
('Spinach', 'Spring'),
('Strawberries', 'Spring'),
('Swiss Chard', 'Spring'),
('Turnips', 'Spring'),
('Halibut', 'Spring'),
('Sablefish', 'Spring'),
('Beets', 'Summer'),
('Bell Peppers', 'Summer'),
('Blackberries', 'Summer'),
('Blueberries', 'Summer'),
('Cantaloupe', 'Summer'),
('Carrots', 'Summer'),
('Celery', 'Summer'),
('Cherries', 'Summer'),
('Corn', 'Summer'),
('Cucumbers', 'Summer'),
('Eggplant', 'Summer'),
('Garlic', 'Summer'),
('Green Beans', 'Summer'),
('Honeydew Melon', 'Summer'),
('Lemons', 'Summer'),
('Lima Beans', 'Summer'),
('Limes', 'Summer'),
('Mangos', 'Summer'),
('Okra', 'Summer'),
('Peaches', 'Summer'),
('Plums', 'Summer'),
('Raspberries', 'Summer'),
('Strawberries', 'Summer'),
('Summer Squash', 'Summer'),
('Tomatillos', 'Summer'),
('Tomatoes', 'Summer'),
('Watermelon', 'Summer'),
('Zucchini', 'Summer'),
('Albacore tuna', 'Summer'),
('Anchovies', 'Summer'),
('Dungeness crab', 'Summer'),
('Halibut', 'Summer'),
('Oregon pink shrimp', 'Summer'),
('Sablefish', 'Summer'),
('Green Beans', 'Fall'),
('Kale', 'Fall'),
('Kiwifruit', 'Fall'),
('Lemons', 'Fall'),
('Lettuce', 'Fall'),
('Limes', 'Fall'),
('Mangos', 'Fall'),
('Mushrooms', 'Fall'),
('Onions', 'Fall'),
('Parsnips', 'Fall'),
('Pears', 'Fall'),
('Peas', 'Fall'),
('Pineapples', 'Fall'),
('Potatoes', 'Fall'),
('Pumpkin', 'Fall'),
('Radishes', 'Fall'),
('Raspberries', 'Fall'),
('Rutabagas', 'Fall'),
('Spinach', 'Fall'),
('Sweet Potatoes', 'Fall'),
('Yams', 'Fall'),
('Swiss Chard', 'Fall'),
('Turnips', 'Fall'),
('Winter Squash', 'Fall'),
('Anchovies', 'Fall'),
('Dungeness crab', 'Fall'),
('Halibut', 'Fall'),
('Oregon pink shrimp', 'Fall'),
('Sablefish', 'Fall'),
('Spiny lobster', 'Fall'),
('Apples', 'Winter'),
('Avocados', 'Winter'),
('Bananas', 'Winter'),
('Beets', 'Winter'),
('Brussels Sprouts', 'Winter'),
('Cabbage', 'Winter'),
('Carrots', 'Winter'),
('Celery', 'Winter'),
('Collard Greens', 'Winter'),
('Grapefruit', 'Winter'),
('Kale', 'Winter'),
('Kiwifruit', 'Winter'),
('Leeks', 'Winter'),
('Lemons', 'Winter'),
('Limes', 'Winter'),
('Onions', 'Winter'),
('Oranges', 'Winter'),
('Parsnips', 'Winter'),
('Pears', 'Winter'),
('Pineapples', 'Winter'),
('Potatoes', 'Winter'),
('Pumpkin', 'Winter'),
('Rutabagas', 'Winter'),
('Sweet Potatoes', 'Winter'),
('Yams', 'Winter'),
('Swiss Chard', 'Winter'),
('Turnips', 'Winter'),
('Winter Squash', 'Winter'),
('Dungeness crab', 'Winter'),
('Spiny lobster', 'Winter'),
('Salt','Not Applicable'),
('All-Purpose Flour','Not Applicable'),
('Whole Wheat Flour','Not Applicable'),
('Bread Flour','Not Applicable'),
('Sugar','Not Applicable'),
('Brown Sugar','Not Applicable'),
('Baking Sugar','Not Applicable'),
('Black Pepper','Not Applicable'),
('White Pepper','Not Applicable'),
('White Vinegar','Not Applicable'),
('Balsamic Vinegar','Not Applicable'),
('Apple Cider Vinegar','Not Applicable'),
('Baking Soda','Not Applicable'),
('Baking Powder','Not Applicable'),
('Chicken','Not Applicable'),
('Pork','Not Applicable'),
('Beef','Not Applicable'),
('Cocoa Powder','Not Applicable'),
('Cream of Tartar','Not Applicable'),
('Olive Oil','Not Applicable'),
('Peanut Oil','Not Applicable'),
('Coconut Oil','Not Applicable'),
('Canola Oil','Not Applicable'),
('Basil','Not Applicable'),
('Oregano','Not Applicable'),
('Parsley','Not Applicable'),
('Garlic Powder','Not Applicable'),
('Onion Powder','Not Applicable'),
('Nutmeg','Not Applicable'),
('Chili Powder','Not Applicable'),
('Chili Flakes','Not Applicable'),
('Cumin','Not Applicable'),
('Thyme','Not Applicable'),
('Fennel','Not Applicable'),
('Vanilla Extract','Not Applicable'),
('Almond Extract','Not Applicable'),
('Mint Extract','Not Applicable'),
('Orange Extract','Not Applicable'),
('Rum Extract','Not Applicable'),
('Soy Sauce','Not Applicable'),
('Worcestershire Sauce','Not Applicable'),
('Vegetable Stock','Not Applicable'),
('Beef Stock','Not Applicable'),
('Chicken Stock','Not Applicable'),
('Shrimp Stock','Not Applicable'),
('Pumpkin Seeds','Not Applicable'),
('Sunflower Seeds','Not Applicable'),
('Macadamia Nuts','Not Applicable'),
('Almonds','Not Applicable'),
('Slivered Almonds','Not Applicable'),
('Ground Almonds','Not Applicable'),
('Walnuts','Not Applicable'),
('Pine Nuts','Not Applicable'),
('Cashews','Not Applicable'),
('Pecans','Not Applicable'),
('Peanut Butter','Not Applicable'),
('Peanuts','Not Applicable'),
('Instant Coffee','Not Applicable'),
('Coffee','Not Applicable'),
('Water','Not Applicable'),
('Feta','Not Applicable'),
('Medium Cheddar','Not Applicable'),
('Sharp Cheddar','Not Applicable'),
('Parmesan','Not Applicable'),
('Shredded Parmesan','Not Applicable'),
('Grated Parmesan','Not Applicable'),
('Cream Cheese','Not Applicable'),
('Mozzarella','Not Applicable'),
('Shredded Mozzarella','Not Applicable'),
('Eggs','Not Applicable'),
('Bacon','Not Applicable'),
('Salami','Not Applicable'),
('Pepperoni','Not Applicable'),
('Hot Dogs','Not Applicable'),
('Dill','Not Applicable'),
('Pickles','Not Applicable'),
('Lemon Juice','Not Applicable'),
('Lime Juice','Not Applicable'),
('Mayonnaise','Not Applicable'),
('Almond Milk','Not Applicable'),
('Coconut Milk','Not Applicable'),
('Ketchup','Not Applicable'),
('Yellow Mustard','Not Applicable'),
('Relish','Not Applicable'),
('Ginger','Not Applicable'),
('Sesame Oil','Not Applicable'),
('Chili Oil','Not Applicable'),
('Rice Vinegar','Not Applicable'),
('Dijon Mustard','Not Applicable'),
('Hot Sauce','Not Applicable'),
('Egg Yolks','Not Applicable'),
('Egg Whites','Not Applicable'),
('Bay Leaves','Not Applicable'),
('Cayenne Pepper','Not Applicable'),
('Crushed Red Pepper','Not Applicable'),
('Coriander','Not Applicable'),
('Paprika','Not Applicable'),
('Rosemary','Not Applicable'),
('Cinnamon','Not Applicable'),
('Cloves','Not Applicable'),
('Allspice','Not Applicable'),
('Curry Powder','Not Applicable'),
('Italian Seasoning','Not Applicable'),
('Chickpeas','Not Applicable'),
('Kidney Beans','Not Applicable'),
('Salsa','Not Applicable'),
('Breadcrumbs','Not Applicable'),
('Panko','Not Applicable'),
('Couscous','Not Applicable'),
('Red Lentils','Not Applicable'),
('Green Lentils','Not Applicable'),
('Pasta','Not Applicable'),
('Whole Wheat Pasta','Not Applicable'),
('White Rice','Not Applicable'),
('Brown Rice','Not Applicable'),
('Oats','Not Applicable'),
('Barley','Not Applicable'),
('Millet','Not Applicable'),
('Quinoa','Not Applicable'),
('Wheatberry','Not Applicable'),
('Cornstarch','Not Applicable'),
('Honey','Not Applicable'),
('Butter','Not Applicable'),
('Flour Tortillas','Not Applicable'),
('Corn Tortillas','Not Applicable'),
('Raisins','Not Applicable'),
('Tomato Paste','Not Applicable'),
('Yogurt','Not Applicable'),
('Red Wine','Not Applicable'),
('Beer','Not Applicable'),
('Yeast','Not Applicable'),
('Corn Syrup','Not Applicable'),
('Anchovies','Not Applicable'),
('Farro','Not Applicable'),
('Cardamom','Not Applicable'),
('Garam Masala','Not Applicable'),
('Mustard Seed','Not Applicable'),
('Milk','Not Applicable');

