var seasonalFoods = [{
    'season': 'Spring',
    'foods': [
      'Apples',
      'Apricots',
      'Asparagus',
      'Avocados',
      'Bananas',
      'Broccoli',
      'Cabbage',
      'Carrots',
      'Celery',
      'Collard Greens',
      'Garlic',
      'Kale',
      'Kiwifruit',
      'Lemons',
      'Lettuce',
      'Limes',
      'Mushrooms',
      'Onions',
      'Peas',
      'Pineapples',
      'Radishes',
      'Rhubarb',
      'Spinach',
      'Strawberries',
      'Swiss Chard',
      'Turnips',
      'Halibut',
      'Sablefish'
    ]
  },
  {
    'season': 'Summer',
    'foods': [
      'Apples',
      'Apricots',
      'Avocados',
      'Bananas',
      'Beets',
      'Bell Peppers',
      'Blackberries',
      'Blueberries',
      'Cantaloupe',
      'Carrots',
      'Celery',
      'Cherries',
      'Corn',
      'Cucumbers',
      'Eggplant',
      'Garlic',
      'Green Beans',
      'Honeydew Melon',
      'Lemons',
      'Lima Beans',
      'Limes',
      'Mangos',
      'Okra',
      'Peaches',
      'Plums',
      'Raspberries',
      'Strawberries',
      'Summer Squash',
      'Tomatillos',
      'Tomatoes',
      'Watermelon',
      'Zucchini',
      'Albacore tuna',
      'Anchovies',
      'Dungeness crab',
      'Halibut',
      'Oregon pink shrimp',
      'Sablefish'
    ]
  },
  {
    'season': 'Fall',
    'foods': [
      'Apples',
      'Bananas',
      'Beets',
      'Bell Peppers',
      'Broccoli',
      'Brussels Sprouts',
      'Cabbage',
      'Carrots',
      'Cauliflower',
      'Celery',
      'Collard Greens',
      'Cranberries',
      'Garlic',
      'Ginger',
      'Grapes',
      'Green Beans',
      'Kale',
      'Kiwifruit',
      'Lemons',
      'Lettuce',
      'Limes',
      'Mangos',
      'Mushrooms',
      'Onions',
      'Parsnips',
      'Pears',
      'Peas',
      'Pineapples',
      'Potatoes',
      'Pumpkin',
      'Radishes',
      'Raspberries',
      'Rutabagas',
      'Spinach',
      'Sweet Potatoes',
      'Yams',
      'Swiss Chard',
      'Turnips',
      'Winter Squash',
      'Anchovies',
      'Dungeness crab',
      'Halibut',
      'Oregon pink shrimp',
      'Sablefish',
      'Spiny lobster',
    ]
  },
  {
    'season': 'Winter',
    'foods': [
      'Apples',
      'Avocados',
      'Bananas',
      'Beets',
      'Brussels Sprouts',
      'Cabbage',
      'Carrots',
      'Celery',
      'Collard Greens',
      'Grapefruit',
      'Kale',
      'Kiwifruit',
      'Leeks',
      'Lemons',
      'Limes',
      'Onions',
      'Oranges',
      'Parsnips',
      'Pears',
      'Pineapples',
      'Potatoes',
      'Pumpkin',
      'Rutabagas',
      'Sweet Potatoes',
      'Yams',
      'Swiss Chard',
      'Turnips',
      'Winter Squash',
      'Dungeness crab',
      'Spiny lobster',
    ]
  }
]
